version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          context: opensource
          filters:
            branches:
              only:
                - master
          requires:
            - test